### PR TITLE
Set default crawler

### PR DESCRIPTION
**Pull request by maxhelias**
Set the default crawler if it is not defined in the constructor of SecurityChecker

### CODE REVIEW

**Comment by fabpot** [comment]
I can see that this is related to symfony/recipes#435

**Comment by maxhelias** [comment]
Yes, I have my Symfony Console that is broken.
And for the corrected we can either add the Crawler as a service in the Symfony project or apply this fix which I think will cover more cases (excluding Symfony)

Error :
```

**Comment by xabbuh** [comment]
IMO this change does look reasonable. There is just one `Crawler` right now which isn't even configurable. So manual injection would basically be the same. Also it is inline with how the current code for 4.1 looks like.

**Comment by fabpot** [comment]
As a side note, you should use the 4.1 branch. The master branch is not released yet.

**Comment by fabpot** [comment]
Thank you @maxhelias.

**Pull request merged**
