### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by streichsbaer**
This PR adds a Dockerfile.

Building the Dockerfile can be done with:

- `docker build -t sensiolabs/security-checker .`

Running the command:

- `docker run -v /path/to/code/:/opt/mount/ sensiolabs/security-checker:latest`
- `docker run -v /path/to/code/:/opt/mount/ sensiolabs/security-checker:latest --format=json`

### CODE REVIEW

**Comment by maxhelias** [comment]
There is already a discussion about this #112

**Comment by streichsbaer** [comment]
Thanks for the response @maxhelias. I only looked at the open issues.

I guess the main difference to #112 is that the `Dockerfile` is part of the repo and can be a viable alternative to run `security-checker`.

Let me know if you don't see the value of it, then I'll close it.

Cheers,
Stefan

**Comment by maxhelias** [comment]
I don't think I can judge the value of his. I any case it seems to be a need.
Also see the usage with the new Symfony CLI in #144 maybe it could help

**Comment by fabpot** [comment]
I think using the Symfony CLI would be much better as it consists of a single binary without dependency. Let's close.

**Comment by streichsbaer** [comment]
Noted, thanks for the update @fabpot and @maxhelias.

**Pull request closed without merging**
