### PR TITLE
Require ctype polyfill

### LINKED ISSUE #163: Call to undefined function SensioLabs\Security\ctype_digit()
Alpine Linux v3.9
PHP 7.2.18
composer.phar global require --no-progress sensiolabs/security-checker
SensioLabs Security Checker 6.0
$ cd /home/user/.composer
$ vendor/bin/security-checker security:check -vvv
PHP Fatal error:  Uncaught Error: Call to undefined function SensioLabs\Security\ctype_digit() in /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler.php:67
Stack trace:
#0 /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php(53): SensioLabs\Security\Crawler->check('composer.lock', 'ansi', Array)
#1 /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Command/SecurityCheckerCommand.php(92): SensioLabs\Security\SecurityChecker->check('composer.lock', 'ansi')
#2 /home/user/.composer/vendor/symfony/console/Command/Command.php(255): SensioLabs\Security\Command\SecurityCheckerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/user/.composer/vendor/symfony/console/Application.php(921): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/user/.comp in /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler.php on line 67

### PR DESCRIPTION
**Pull request by BackEndTea**
Fixes #163

### CODE REVIEW

**Comment by Nardberjean** [comment]
Thanks!

**Comment by Nardberjean** [comment]
I am not sure if adding or ext-ctype may help prevent conflits in some installation cases, where other packages may require ext-ctypes only and conflict with the polyfill.

**Comment by Nardberjean** [comment]
The polyfill is probably not loading when the extension is present and I see that symfony/skeleton and symfony/website-skeleton are replacing the extension so conflicts seems to be avoided.

**Comment by Nardberjean** [comment]
Looks like if adding the "or" would make it more readable for slow humains like me.

**Comment by fabpot** [comment]
Thank you @BackEndTea.

**Comment by BackEndTea** [comment]
Thank you @fabpot & @nicolas-grekas

**Pull request merged**
