### PR TITLE
Update security.sensiolabs.org.crt following cert upgrade on production

### PR DESCRIPTION
**Pull request by smaftoul**

### CODE REVIEW

**Comment by blaugueux** [comment]
It doesn't work for us on OSX

**Comment by xabbuh** [comment]
@blaugueux What exactly doesn't work? Do you see an error message?

**Comment by blaugueux** [comment]
@xabbuh here is a screenshot
screen shot 2015-05-06 at 22 29 00

**Comment by romainneutron** [comment]
@blaugueux Could you run the command with `-vvv` option and give the stacktrace?

**Comment by blaugueux** [comment]
screenshot
Even in verbose more I don't have new details. It works if i comment this line: https://github.com/sensiolabs/security-checker/blob/master/SensioLabs/Security/SecurityChecker.php#L90

**Comment by smaftoul** [comment]
@blaugueux are you using the latest version ?

**Comment by blaugueux** [comment]
yep!

`composer.lock`
```json
    {
            "name": "sensiolabs/security-checker",
            "version": "v2.0.2",
            "source": {
                "type": "git",
                "url": "https://github.com/sensiolabs/security-checker.git",
                "reference": "cecb1397087dc9c733796eda6e9d121336039cdc"
            },...
```

**Comment by ErichHartmann** [comment]
Same issue with Symfony 2.6.7:

```
[2015-05-11 10:42:27] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".  
[2015-05-11 10:42:27] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".  
[2015-05-11 10:42:27] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".  
                                                                                       
  An error occurred: SSL certificate problem: unable to get local issuer certificate.  
```

**Comment by smaftoul** [comment]
@blaugueux @ErichHartmann please, what is your OS, OS version and openssl version ?

**Comment by blaugueux** [comment]
@smaftoul `OpenSSL 0.9.8zd 8 Jan 2015` on `Mac OSX 10.10.3`

**Comment by smaftoul** [comment]
I hope #38 improve the situation !

**Comment by fabpot** [comment]
Should be fixed now in 2.0.3

**Pull request merged**
