### PR TITLE
Include root certificate in certificate chain

### PR DESCRIPTION
**Pull request by smaftoul**
Some OS or build of openssl seem to not bundle this root certificate.
Adding it make the security checker work and not showing the message `An error occurred: SSL certificate problem: unable to get local issuer certificate.`

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @smaftoul.

**Comment by drAlberT** [comment]
I had to append wget http://curl.haxx.se/ca/cacert.pem to vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt in order to have rid of the bug. version 2.0.3 was still not working


I think the problem should be the intermediate cert, not the root

**Comment by smaftoul** [comment]
@drAlberT thanks for your feedback and tests.
Do you have /etc/ssl/certs/AddTrust_External_Root.pem or /etc/ssl/certs/157753a5.0 on your system ? If yes, can you replace `vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt` with this file and tell me if it works ?
Thanks !

**Comment by drAlberT** [comment]
@smaftoul one more info:

on 2.0.3 it works if run as root, it doesn't if run as normal user .. going to run your test .. stay tuned

**Comment by drAlberT** [comment]
Bingo .. it works appending AddTrust_External_Root :+1:

**Comment by drAlberT** [comment]
The last info:

root reason of my issue was a too rescrictive permission to /etc/ssl dir .. not being the distro permissions.

So normally there should be any problem, my though is to append the root cert anyway :)

Thank you

**Comment by smaftoul** [comment]
@drAlberT can you please retry with no permissions on /etc/ssl and not by appending  to the chain , but just having the content of AddTrust_External_Root.pem in the crt file ? Just ton confirm it works with no certificate installed on the machine, and with only the root certificate in the chain / cafile.
Thanks !

**Comment by drAlberT** [comment]
@smaftoul Already checked, of course ;)  For me it works.

It was working just appending the root cert *before* I argued my problem was in dir permissions

**Pull request merged**
