### PR TITLE
Updated the style of the security:check command

### PR DESCRIPTION
**Pull request by javiereguiluz**
security_checker

### CODE REVIEW

**Comment by xabbuh** [comment]
This needs special treatment for Symfony 2.3.

**Comment by javiereguiluz** [comment]
I propose to do the same as for SwiftMailerBundle's commands: block this PR until May 2016, when Symfony 2.3 will die.

**Comment by relaxnow** [comment]
@javiereguiluz / @xabbuh it is well past May 2016, can this be merged?

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request merged**
