### PR TITLE
Fix #51 missing setEndPoint and setTimeout methods on securityChecker

### LINKED ISSUE #51: timeout command parameter crash the checker
The timeout command parameter in the security-check generate the following error:

```
$ php bin/security-checker security:check --timeout=10
PHP Fatal error:  Call to undefined method SensioLabs\Security\SecurityChecker::setTimeout() in /var/www/voodoo/vendor/sensiolabs/security-checker/SensioLabs/Security/Command/SecurityCheckerCommand.php on line 79
PHP Stack trace:
PHP   1. {main}() /var/www/voodoo/vendor/sensiolabs/security-checker/security-checker:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/voodoo/vendor/sensiolabs/security-checker/security-checker:32
PHP   3. Symfony\Component\Console\Application->doRun() /var/www/voodoo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /var/www/voodoo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /var/www/voodoo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:878
PHP   6. SensioLabs\Security\Command\SecurityCheckerCommand->execute() /var/www/voodoo/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
```

### PR DESCRIPTION
**Pull request by opalenet-yann**
Add missing `setTimeout($timeout)` and `setEndPoint($endPoint)` in `SensioLabs/Security/SecurityChecker.php`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
That's probably intentional isn't it. They're meant to be immutable arn't they?

**Comment by fabpot** [comment]
Indeed, that's intentional, you should use set them on a crawler and pass it to the security checker instead. That's why I bumped the version of the package to a new major one by the way.

**Comment by fabpot** [comment]
I've just read your related issue. I'm going to have a look at it now.

**Comment by fabpot** [comment]
Ok, that's not that easy to fix. I think a better fix would be to add a `getCrawler` on the security checker and change the command accordingly. Can you try that?

**Comment by opalenet-yann** [comment]
Here you go.

**Comment by fabpot** [comment]
Thank you @opalenet-yann.

**Pull request closed without merging**
