### PR TITLE
renamed argument from lock to lockfile

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by fabpot** [comment]
That's a huge BC break for people using this for automation. Not sure it is worth it.

**Comment by OskarStark** [comment]
i thought these arguments are just ordered and the naming is not so important!

thanks for the info

**Comment by fabpot** [comment]
Indeed, my mistake, this is an argument, not an option.

**Comment by OskarStark** [comment]
i stumpled upon this as i looked at the help of the command and lock was a bit confusing for me...

**Comment by fabpot** [comment]
Thank you @OskarStark.

**Comment by OskarStark** [comment]
Thanks @fabpot

**Pull request merged**
