### PR TITLE
Added Usage for docker image

### PR DESCRIPTION
**Pull request by rakshazi**
Hello!
We created docker image for security checker. It's must-have for dockerized projects, to run such tools as docker images on CI/CD server

PS: If you want, I can add security checker maintainers to docker hub repo team, so you will have control on it

### CODE REVIEW

**Comment by rakshazi** [comment]
Ping

**Comment by maxhelias** [comment]
I am not convinced of the usefulness of a docker image for this need. 
For Symfony project, it has a recipe, just need to require the package in dev only and you can do the CI/CD similarly and faster.
And for other project, the configuration is minimal or nonexistent, which in my opinion does not need to be containerized

**Comment by rakshazi** [comment]
Well, i have another example - in our company 10+ projects use security checker with docker image.
The main idea of docker that you can run it with one-line command on any system and you don't even need PHP/composer/etc. installed.
In some environments (like our fully dockerized) standard way with phar or composer not usable at all, that's why I suggest you to include docker as one of the available ways to use

**Comment by rakshazi** [comment]
Yes, but it will be a mess :(
Here is how we use it right now: https://github.com/frameworkwtf/skeleton/blob/master/.gitlab-ci.yml#L45
And `security-checker` script is: https://github.com/titanium-codes/docker/blob/master/Dockerfile#L12

**Comment by fabpot** [comment]
I agree with @maxhelias. And I'm not comfortable with linking to a Docker image I cannot review. Let's close.

**Comment by fabpot** [comment]
For the record, a better alternative is to use the `symfony` binary, which has no dependencies (https://symfony.com/cloud/download).

**Pull request closed without merging**
